package br.com.vrfortaleza.integracaoapi.api.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

@Data
public class ProdutoDTO {
    private Integer id;
    private Integer idTipoMovimentacao;
    private Integer idCenarioFiscal;
    private String descricaoTipoMovimentacao;
    private Integer numeroItem;
    private Integer idProduto;
    private String descricaoProduto;
    private Integer idCodigoBarras;
    private String codigoBarras;
    private String quantidade;
    private String quantidadeProduto;
    private String quantidadeVenda;
    private String quantidadeCompra;
    private String codEmbalagem;
    private String codEmbalagemNFe;
    private String valorUnitario;
    private String valorUnitarioProduto;
    private String valorTotalBruto;
    private @JsonProperty("NCM") String NCM;
    private Integer excecaoNCM;
    private @JsonProperty("CEST") String CEST;
    private @JsonProperty("CFOP") String CFOP;
    private @JsonProperty("CSTICMS") String CSTICMS;
    private String valorOutrasDespesas;
    private String valorDesconto;
    private String valorFrete;
    private String valorSeguro;
    private String valorIPI;
    private String custoUnitarioProduto;
    private String custoUnitarioAnterior;
    private String custoUnitarioSemImpostoAnterior;
    private String precoComum;
    private String custoCompra;
    private Integer origemMercadoria;
    private Integer modalidadeBaseCalculo;
    private String valorIsento;
    private String reducaoICMS;
    private String valorBaseCalculoICMS;
    private @JsonProperty("ICMS") String ICMS;
    private String valorICMS;
    private String diferido;
    private String valorICMSDiferido;
    private @JsonProperty("FCP") String FCP;
    private String valorFCP;
    private @JsonProperty("ICMSDesonerado") String ICMSDesonerado;
    private String valorICMSDesonerado;
    private String valorIVA;
    private String percentualIVA;
    private String reducaoICMSST;
    private String valorBaseCalculoICMSST;
    private @JsonProperty("ICMSST") String ICMSST;
    private String valorICMSST;
    private @JsonProperty("FCPST") String FCPST;
    private String valorFCPST;
    private String valorBaseCalculoICMSSTRetido;
    private String valorICMSSTRetido;
    private String valorFCPSTRetido;
    private Integer idLocalEstoque;
    private String cstpiscofins;
    private String valorBaseCalculoPISCOFINS;
    private String pis;
    private String valorPIS;
    private String cofins;
    private String valorCOFINS;
    private Boolean custoAtualizado;
    private String valorBonificado;
    private String valorBonificacaoDisponivel;
    private String baseCalculoICMSSTRetAnterior;
    private String valorICMSSTRetAnterior;
    private String valorFCPSTRetAnterior;
}
